# Generated by Django 3.1.2 on 2021-05-07 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Razorpay_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rzp_order_id', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField(null=True)),
                ('rzp_payment_id', models.CharField(blank=True, max_length=60, null=True)),
                ('method', models.CharField(max_length=20, null=True)),
                ('payment_email', models.EmailField(max_length=254, null=True)),
                ('payment_contact', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'Razorpay',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('razorpay_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.razorpay_data')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
